server:
  port: 8080
  servlet:
    context-path: /api
spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: bnu_tiku_backend
  profiles:
    active: local
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ht.bnu_tiku_backend.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

